export const MAX_OUTER = Number(process.env.TIMETABLE_MAX_OUTER ?? 3)
export const MAX_CODER_INNER = Number(process.env.TIMETABLE_MAX_CODER_INNER ?? 4)

export const PREVIOUS_SOLVER_HEAD_LINES = 80
export const PREVIOUS_SOLVER_TAIL_LINES = 40
export const PREVIOUS_SOLVER_TRUNCATE_CHARS = 4_000
export const AUTHOR_PROMPT_LIMIT_CHARS = 20_000
export const VERIFY_PROMPT_COMPACT_LIMIT_CHARS = 30_000
export const VERIFY_PROMPT_HARD_LIMIT_CHARS = 60_000

export const LLM_RETRY_DELAY_MS = 1_500
export const LLM_RATE_LIMIT_RETRY_DELAY_MS = 2_000
