sonar.projectKey=timetable
sonar.projectName=timetable
sonar.sourceEncoding=UTF-8
sonar.sources=src,electron,scripts
sonar.exclusions=**/.next/**,**/node_modules/**,**/release/**,**/.venv-build/**,**/python-dist/**,**/*.tsbuildinfo,**/python/**
