/**
 * python-bridge.ts
 * High-level bridge between the local AI agent and the Python execution host.
 *
 * In the final implementation this talks to the main process via IPC.
 * For now it contains the interface + a dev stub.
 */

import type { AgentInputPayload, ExecutionResult } from './types';

export interface PythonBridgeOptions {
  timeoutMs?: number;
  signal?: AbortSignal;
}

/**
 * Execute a piece of Python code generated by the Coder.
 * The code will be run inside the `code_executor` binary with the provided input.
 */
export async function executeGeneratedCode(
  code: string,
  input: AgentInputPayload,
  options: PythonBridgeOptions = {}
): Promise<ExecutionResult> {
  const timeout = options.timeoutMs ?? 180_000;

  // In production this will be an IPC call to the main process
  // which actually spawns the bundled binary.
  if (typeof window !== 'undefined' && (window as any).electron?.python?.executeCode) {
    return (window as any).electron.python.executeCode(code, input, timeout);
  }

  // DEV STUB - only for early development before IPC is wired
  console.warn('[python-bridge] Using DEV STUB. Real IPC not wired yet.');
  await new Promise((r) => setTimeout(r, 300));

  // Return a fake successful result so the rest of the agent can be developed
  return {
    success: true,
    has_solution: true,
    stdout: 'SOLUTION FOUND\nFake schedule generated in dev stub',
    stderr: '',
    execution_time_ms: 1234,
    error_type: null,
    result: {
      classes: ['6A', '6B'],
      days: ['Thứ 2', 'Thứ 3'],
      periods: [1, 2, 3],
      schedule: [
        { class: '6A', day: 'Thứ 2', period: 1, subject: 'Toán', teacher: 'Sơn' },
      ],
    },
  };
}
