/**
 * python-bridge.ts
 * High-level bridge between the local AI agent and the Python execution host.
 *
 * In the final implementation this talks to the main process via IPC.
 * For now it contains the interface + a dev stub.
 */

import type { AgentInputPayload, ExecutionResult } from './types';

export interface PythonBridgeOptions {
  timeoutMs?: number;
  signal?: AbortSignal;
}

/**
 * Execute a piece of Python code generated by the Coder.
 * The code will be run inside the `code_executor` binary with the provided input.
 */
export async function executeGeneratedCode(
  code: string,
  input: AgentInputPayload,
  options: PythonBridgeOptions = {}
): Promise<ExecutionResult> {
  const timeout = options.timeoutMs ?? 180_000;

  // In production this will be an IPC call to the main process
  // which actually spawns the bundled binary.
  if (typeof window !== 'undefined' && (window as any).electron?.python?.executeCode) {
    return (window as any).electron.python.executeCode(code, input, timeout);
  }

  throw new Error(
    '[python-bridge] Python executor IPC is not available. Please run inside Electron app (with preload exposing window.electron.python.executeCode) or wire a server execution route.'
  );
}
