/**
 * python-bridge.ts
 * High-level bridge between the local AI agent and the Python execution host.
 *
 * In the final implementation this talks to the main process via IPC.
 * For now it contains the interface + a dev stub.
 */

import type { ExecutionResult } from './types';

export interface PythonBridgeOptions {
  timeoutMs?: number;
  solverWorkers?: number;
  signal?: AbortSignal;
}

/**
 * Execute a piece of Python code generated by the Coder.
 * The code will be run inside the `code_executor` binary with the provided input.
 */
export async function executeGeneratedCode(
  code: string,
  input: unknown,
  options: PythonBridgeOptions = {}
): Promise<ExecutionResult> {
  const timeout = options.timeoutMs ?? 360_000;

  // In production this will be an IPC call to the main process
  // which actually spawns the bundled binary.
  if (typeof window !== 'undefined' && window.electron?.python?.executeCode) {
    return window.electron.python.executeCode(code, input, timeout, options.solverWorkers);
  }

  // Web fallback: call server-side executor route.
  if (typeof window !== 'undefined') {
    const response = await fetch('/api/ai/python-execute', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        code,
        input,
        timeoutMs: timeout,
        solverWorkers: options.solverWorkers,
      }),
    });

    const payload = await response.json().catch(() => null);

    if (!response.ok || !payload?.ok || !payload?.result) {
      throw new Error(
        payload?.error ||
          `[python-bridge] Server executor failed with HTTP ${response.status}`
      );
    }

    return payload.result as ExecutionResult;
  }

  throw new Error(
    '[python-bridge] Python executor IPC is not available. Please run inside Electron app (with preload exposing window.electron.python.executeCode) or wire a server execution route.'
  );
}
