/**
 * skeleton-injector.ts
 *
 * Loads the canonical CP-SAT solver skeleton from `/templates/solver_skeleton.py`
 * (served by Next.js from `public/templates/`, regenerated by
 * `scripts/sync_solver_template.mjs` on `predev`/`prebuild`/`pretest`).
 *
 * The deterministic solve path consumes the skeleton as-is: the legacy
 * `AI_FILL_HERE` marker and `injectConstraintCode` were removed in M9 because
 * the IR compiler (`ir_compiler.py` + `ir_eval.py` inside the skeleton) is
 * the single source of truth for custom_dsl encoding.
 *
 * Also exposes `syntaxCheckPython` / `astCheckPython` helpers backed by the
 * Electron bridge or the HTTP fallback at `/api/ai/python-syntax-check` and
 * `/api/ai/python-ast-check`.
 */

export async function loadSolverSkeleton(): Promise<string> {
  const publicResponse = await fetch('/templates/solver_skeleton.py').catch(() => null);
  if (publicResponse?.ok) {
    return publicResponse.text();
  }

  const routeResponse = await fetch('/api/ai/solver-skeleton').catch(() => null);
  if (!routeResponse?.ok) {
    throw new Error('Unable to load solver skeleton template.');
  }
  return routeResponse.text();
}

type PythonCheckResult = {
  ok?: boolean;
  error?: string;
  errorDigest?: string;
  stderr?: string;
  stdout?: string;
}

type PythonCheckBridge = {
  syntaxCheck?: (code: string) => Promise<PythonCheckResult>
  astCheck?: (code: string) => Promise<PythonCheckResult>
}

function pythonCheckError(result: PythonCheckResult): string | undefined {
  return result.error || result.errorDigest || result.stderr || result.stdout;
}

function pythonCheckBridge(): PythonCheckBridge | null {
  if (typeof window === 'undefined') return null
  return (window.electron?.python ?? null) as PythonCheckBridge | null
}

export async function syntaxCheckPython(code: string): Promise<{ ok: boolean; error?: string }> {
  try {
    const bridge = pythonCheckBridge()
    if (bridge?.syntaxCheck) {
      const result = await bridge.syntaxCheck(code)
      return { ok: Boolean(result.ok), error: pythonCheckError(result) }
    }

    const response = await fetch('/api/ai/python-syntax-check', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ code }),
    });

    const payload = (await response.json()) as {
      ok?: boolean;
      result?: { ok?: boolean; error?: string };
      error?: string;
    };

    if (!response.ok || !payload.ok || !payload.result) {
      return { ok: false, error: payload.error || 'Python syntax check API failed.' };
    }

    return {
      ok: Boolean(payload.result.ok),
      error: payload.result.error,
    };
  } catch (error) {
    return {
      ok: false,
      error: error instanceof Error ? error.message : 'Unable to run Python syntax check.',
    };
  }
}

export async function astCheckPython(code: string): Promise<{ ok: boolean; error?: string }> {
  try {
    const bridge = pythonCheckBridge()
    if (bridge?.astCheck) {
      const result = await bridge.astCheck(code)
      return { ok: Boolean(result.ok), error: pythonCheckError(result) }
    }

    const response = await fetch('/api/ai/python-ast-check', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ code }),
    });

    const payload = (await response.json()) as {
      ok?: boolean;
      result?: { ok?: boolean; error?: string };
      error?: string;
    };

    if (!response.ok || !payload.ok || !payload.result) {
      return { ok: false, error: payload.error || 'AST check API failed.' };
    }

    return {
      ok: Boolean(payload.result.ok),
      error: payload.result.error,
    };
  } catch (error) {
    return {
      ok: false,
      error: error instanceof Error ? error.message : 'AST check failed.',
    };
  }
}

