#!/usr/bin/env python3

import json
import shutil
import subprocess
import sys
import tempfile
import time
import traceback
from pathlib import Path
from typing import Any

TIMEOUT_SECONDS = 360
MAX_STDOUT_LINES = 100


def _truncate_output(text: str, max_lines: int = MAX_STDOUT_LINES) -> str:
    lines = text.splitlines()
    if len(lines) <= max_lines:
        return text
    head = "\n".join(lines[:max_lines])
    return f"{head}\n...[truncated {len(lines) - max_lines} lines]"


def _digest_error(stderr: str, max_length: int = 800) -> str:
    lines = [line.strip() for line in stderr.splitlines() if line.strip()]
    focused = "\n".join(lines[-12:])
    return focused[:max_length]


def _map_status(raw: str) -> str:
    status = raw.upper()
    if status == "OPTIMAL":
        return "optimal"
    if status == "FEASIBLE":
        return "feasible"
    if status in {"INFEASIBLE", "MODEL_INVALID"}:
        return "infeasible"
    if status in {"UNKNOWN"}:
        return "unknown"
    return "unknown"


def run_user_code(code: str, timeout: int) -> dict[str, Any]:
    started = time.time()
    with tempfile.TemporaryDirectory(prefix="timetable_exec_") as temp_dir:
        workspace = Path(temp_dir)
        input_src = Path.cwd() / "input.json"
        input_dst = workspace / "input.json"
        solver_path = workspace / "solver_generated.py"
        result_path = workspace / "result.json"

        if input_src.exists():
            shutil.copy2(input_src, input_dst)
        else:
            input_dst.write_text("{}", encoding="utf-8")

        solver_path.write_text(code, encoding="utf-8")

        compile_proc = subprocess.run(
            [sys.executable, "-m", "py_compile", str(solver_path)],
            capture_output=True,
            text=True,
            cwd=workspace,
        )
        if compile_proc.returncode != 0:
            return {
                "phase": "compile",
                "ok": False,
                "status": "crashed",
                "durationMs": int((time.time() - started) * 1000),
                "errorDigest": _digest_error(compile_proc.stderr or compile_proc.stdout),
                "stdout": _truncate_output(compile_proc.stdout or ""),
                "stderr": _truncate_output(compile_proc.stderr or ""),
            }

        try:
            run_proc = subprocess.run(
                [sys.executable, str(solver_path)],
                capture_output=True,
                text=True,
                cwd=workspace,
                timeout=timeout,
            )
        except subprocess.TimeoutExpired as exc:
            return {
                "phase": "run",
                "ok": False,
                "status": "timeout",
                "durationMs": int((time.time() - started) * 1000),
                "errorDigest": f"Execution timed out after {timeout}s",
                "stdout": _truncate_output(exc.stdout or ""),
                "stderr": _truncate_output(exc.stderr or ""),
            }

        stdout = run_proc.stdout or ""
        stderr = run_proc.stderr or ""
        upper_stdout = stdout.upper()
        marker_count = upper_stdout.count("SOLUTION_FOUND")
        no_solution_marker = "NO_SOLUTION:" in upper_stdout

        if marker_count > 1:
            return {
                "phase": "parse",
                "ok": False,
                "status": "crashed",
                "durationMs": int((time.time() - started) * 1000),
                "errorDigest": "Invalid marker count: SOLUTION_FOUND appears more than once.",
                "stdout": _truncate_output(stdout),
                "stderr": _truncate_output(stderr),
            }

        if not result_path.exists():
            return {
                "phase": "parse",
                "ok": False,
                "status": "crashed",
                "durationMs": int((time.time() - started) * 1000),
                "errorDigest": "result.json was not generated by solver.",
                "stdout": _truncate_output(stdout),
                "stderr": _truncate_output(stderr),
            }

        try:
            result_json = json.loads(result_path.read_text(encoding="utf-8"))
        except Exception as exc:
            return {
                "phase": "parse",
                "ok": False,
                "status": "crashed",
                "durationMs": int((time.time() - started) * 1000),
                "errorDigest": f"Invalid result.json format: {exc}",
                "stdout": _truncate_output(stdout),
                "stderr": _truncate_output(stderr),
            }

        schedule = result_json.get("schedule", []) if isinstance(result_json, dict) else []
        status_raw = result_json.get("status", "unknown") if isinstance(result_json, dict) else "unknown"
        status = _map_status(str(status_raw))
        if marker_count == 1:
            status = "optimal" if status == "unknown" else status
        if no_solution_marker and status in {"optimal", "feasible"}:
            status = "infeasible"

        unscheduled: list[str] = []
        if isinstance(result_json, dict) and isinstance(result_json.get("assignments"), list):
            scheduled_ids = {
                str(entry.get("assignmentId"))
                for entry in schedule
                if isinstance(entry, dict) and entry.get("assignmentId") is not None
            }
            unscheduled = [
                str(item.get("id"))
                for item in result_json["assignments"]
                if isinstance(item, dict) and str(item.get("id")) not in scheduled_ids
            ]

        ok = run_proc.returncode == 0 and status in {"optimal", "feasible"}
        digest_source = stderr if stderr.strip() else stdout

        artifact_dir = Path.cwd() / ".ai_results"
        artifact_dir.mkdir(parents=True, exist_ok=True)
        artifact_path = artifact_dir / f"result_{int(time.time() * 1000)}.json"
        artifact_path.write_text(json.dumps(result_json, ensure_ascii=False), encoding="utf-8")

        return {
            "phase": "run",
            "ok": ok,
            "status": status if status in {"optimal", "feasible", "infeasible"} else "unknown",
            "durationMs": int((time.time() - started) * 1000),
            "resultPath": str(artifact_path),
            "resultSummary": {
                "scheduledCount": len(schedule) if isinstance(schedule, list) else 0,
                "unscheduledAssignments": unscheduled,
            },
            "errorDigest": _digest_error(digest_source) if not ok else "",
            "stdout": _truncate_output(stdout),
            "stderr": _truncate_output(stderr),
        }


def main() -> None:
    code = sys.stdin.read()
    if not code.strip():
        print(
            json.dumps(
                {
                    "phase": "parse",
                    "ok": False,
                    "status": "crashed",
                    "durationMs": 0,
                    "errorDigest": "No code received on stdin.",
                    "stdout": "",
                    "stderr": "",
                },
                ensure_ascii=False,
            )
        )
        return

    try:
        result = run_user_code(code, TIMEOUT_SECONDS)
    except Exception:
        result = {
            "phase": "run",
            "ok": False,
            "status": "crashed",
            "durationMs": 0,
            "errorDigest": _digest_error(traceback.format_exc()),
            "stdout": "",
            "stderr": "",
        }
    print(json.dumps(result, ensure_ascii=False))


if __name__ == "__main__":
    main()
