#!/usr/bin/env python3
"""
code_executor.py
Secure(ish) executor for code generated by the local AI agent.

Contract (stdin/stdout):
- Reads the FULL Python source code from stdin.
- Expects `input.json` to already exist in the current working directory.
- Must finish within the timeout enforced by the parent (180s recommended).
- ALWAYS prints exactly ONE JSON object to stdout with the shape defined in types.ts ExecutionResult.

Usage (called by Electron):
    echo '....python code....' | python code_executor.py

The generated code is expected to:
- Read problem data from ./input.json
- Print "SOLUTION FOUND" somewhere on success
- Output the schedule in the agreed JSON format (either to stdout or to a result file that we can parse)
"""

import json
import os
import sys
import subprocess
import tempfile
import time
import traceback
from pathlib import Path
from typing import Any, Dict

TIMEOUT_SECONDS = 180  # Hard safety net (parent should also enforce)


def read_stdin_all() -> str:
    """Read all data from stdin (the generated Python code)."""
    return sys.stdin.read()


def write_temp_code(code: str) -> Path:
    """Write the received code to a temp file in the current working directory."""
    cwd = Path.cwd()
    temp_file = cwd / f"ai_generated_solver_{int(time.time())}.py"
    temp_file.write_text(code, encoding="utf-8")
    return temp_file


def run_user_code(code_path: Path, timeout: int) -> Dict[str, Any]:
    """
    Run the generated Python file with a hard timeout.
    Returns a dict that will be turned into the final JSON.
    """
    start = time.time()
    stdout_chunks: list[str] = []
    stderr_chunks: list[str] = []

    try:
        proc = subprocess.Popen(
            [sys.executable, str(code_path)],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            cwd=Path.cwd(),
        )

        try:
            out, err = proc.communicate(timeout=timeout)
            stdout_chunks.append(out or "")
            stderr_chunks.append(err or "")
            return_code = proc.returncode
        except subprocess.TimeoutExpired:
            proc.kill()
            out, err = proc.communicate()
            stdout_chunks.append(out or "")
            stderr_chunks.append(err or "")
            return {
                "success": False,
                "has_solution": False,
                "stdout": "".join(stdout_chunks),
                "stderr": "".join(stderr_chunks) + f"\n[EXECUTOR] Hard timeout after {timeout}s",
                "execution_time_ms": int((time.time() - start) * 1000),
                "error_type": "timeout",
                "result": None,
            }

        full_stdout = "".join(stdout_chunks)
        full_stderr = "".join(stderr_chunks)

        has_solution = "SOLUTION FOUND" in full_stdout.upper()

        # Try to extract JSON result if the generated code printed it
        result = None
        try:
            # Heuristic: last line that looks like JSON
            for line in reversed(full_stdout.strip().splitlines()):
                line = line.strip()
                if line.startswith("{") and line.endswith("}"):
                    result = json.loads(line)
                    break
        except Exception:
            pass

        return {
            "success": return_code == 0,
            "has_solution": has_solution,
            "stdout": full_stdout,
            "stderr": full_stderr,
            "execution_time_ms": int((time.time() - start) * 1000),
            "error_type": None if return_code == 0 else "exception",
            "result": result,
        }

    except Exception as e:
        return {
            "success": False,
            "has_solution": False,
            "stdout": "".join(stdout_chunks),
            "stderr": "".join(stderr_chunks) + f"\n[EXECUTOR CRASH] {str(e)}\n{traceback.format_exc()}",
            "execution_time_ms": int((time.time() - start) * 1000),
            "error_type": "exception",
            "result": None,
        }
    finally:
        # Best effort cleanup of the temp generated file
        try:
            if code_path.exists():
                code_path.unlink()
        except Exception:
            pass


def main():
    code = read_stdin_all().strip()
    if not code:
        result = {
            "success": False,
            "has_solution": False,
            "stdout": "",
            "stderr": "[EXECUTOR] No code received on stdin",
            "execution_time_ms": 0,
            "error_type": "parse_error",
            "result": None,
        }
        print(json.dumps(result, ensure_ascii=False))
        sys.exit(1)

    # Write code to a temp file inside the job working directory
    code_path = write_temp_code(code)

    # Run it
    exec_result = run_user_code(code_path, TIMEOUT_SECONDS)

    # Always emit exactly one JSON line
    print(json.dumps(exec_result, ensure_ascii=False))


if __name__ == "__main__":
    main()
