name: Build Windows Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    permissions:
      contents: write
    uses: ./.github/workflows/_reusable-windows-build.yml
    with:
      artifact_name: windows-release
      publish_release: ${{ startsWith(github.ref, 'refs/tags/v') }}
